[package]
name = "libc-stdhandle"
version = "0.1.0"
authors = ["CrLF0710 <crlf0710@gmail.com>"]
license = "MIT/Apache-2.0"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1"
